version: '3.7'

services:
  backend:
    container_name: backend
    build: ./backend
    # env_file:
    #   - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      BACKEND_URL: http://backend:3000 

  db:
    image: postgres
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}